### ISSUE TITLE
ffi.cdef signature for 'free()' should change

### ISSUE THREAD

**Issue by Wiladams** [franko/luajit-lang-toolkit#20]
In 'bytecode.lua', there is a ffi.cdef for the 'free()' function that looks like the following:
    int free(void*);

The definition that is in my stdlib.h, and I think the standard, is:
    void   free   ( void * ptr );

Additionally, on Windows, it's not found using ffi.C.free (symbol not found).  I think you might have to pull from a specific library, or from the app itself.

**Comment by franko** [comment]
I guess that the error in the signature of the “free” function is quite harmless but of course we can fix that.

Otherwise I don’t have a clear idea why the function is not found on windows on your system. I guess it depends on some obscure things like the compiler you used for LuaJIT and the MSVCRT library it is linked to.

If you have a clear fix for the linking problem I will be glad to accept it.

Otherwise I’m considering to get rid of the malloc/free stuff in bytecode.lua. Maybe we can use the standard LuaJIT ffi.new function. It is simple to do but I don’t know if I have the time to work on that right now. I you can contribute such a modification and send a pull request I will appreciate.

**Comment by franko** [comment]
Now the problem should be fixed with commit 8b091d6498. I've replaced the malloc/free calls with ffi.new and ffi.copy.

**Comment by Wiladams** [comment]
Great.  I'll try again.

Sent from my Windows Phone
________________________________
