### ISSUE TITLE
lang_loadstring error

### ISSUE THREAD

**Issue by CapsAdmin** [franko/luajit-lang-toolkit#25]
I was curious to see how things would perform and behave if I replaced loadstring in my project and stumbled upon this error:

> print(require("lang.compile").string('something("foo bar"--[[]], foo, bar)'))
false,    luajit-lang-toolkit: stdin:1: ')' expected near '<eof>'

**Comment by franko** [comment]
Hi,

you stumbled on a lexer's bug. Now fixed in git HEAD.

Just an funny note. This error and some similar ones in the lexer come all from the fact that I translated the luajit's lexer which is in C and use a lot of "continue" statements. As this latter statement is missing in Lua I was forced to perform a complicate gymnastic with the control flow and I ended up introducing some bugs.
